//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto_Final_P2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class utilizadores
    {
        public int id_utilizador { get; set; }
        public string nome { get; set; }
        public System.DateTime data_nascimento { get; set; }
        public Nullable<int> idade { get; set; }
        public string morada { get; set; }
        public int numero_predio { get; set; }
        public int numero_andar { get; set; }
        public int cc { get; set; }
    }
}
